//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Components.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public ItemDetail()
        {
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public int Item_ID { get; set; }
        public string Item_Name { get; set; }
        public decimal Item_price { get; set; }
        public string Image_Name { get; set; }
        public string Description { get; set; }
        public string AddedBy { get; set; }
    
        public virtual ICollection<CartDetail> CartDetails { get; set; }
    }
}
